models:
  - model: output/30K_helpful_dpo_safety/helpful_dpo_0.1
    parameters:
      weight: 0.5
  - model: output/30K_helpful_dpo_safety/helpful_dpo_safety_dpo_0.01
    parameters:
      weight: 0.5
merge_method: linear
dtype: bfloat16
